using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
public class CaravanGame:MonoBehaviour{
 enum ScreenId{Home,Map,Loadout,Battle,Result,Shop,Missions,Settings}
 readonly string[] gear={"🏹 قوس","🛡️ درع","🔥 مشعل","🪓 فأس","💧 ماء","🧭 بوصلة","🗡️ سيف","🪙 ذهب"};
 readonly HashSet<int> selected=new HashSet<int>(); Canvas canvas; RectTransform root; int coins=120,level=1,weight;
 [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)] static void Boot(){if(FindObjectOfType<CaravanGame>())return;var g=new GameObject("CaravanGame");DontDestroyOnLoad(g);g.AddComponent<CaravanGame>();}
 void Awake(){var g=new GameObject("Canvas",typeof(Canvas),typeof(CanvasScaler),typeof(GraphicRaycaster));canvas=g.GetComponent<Canvas>();canvas.renderMode=RenderMode.ScreenSpaceOverlay;var s=g.GetComponent<CanvasScaler>();s.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;s.referenceResolution=new Vector2(1080,1920);root=Make("Root",canvas.transform);root.anchorMin=Vector2.zero;root.anchorMax=Vector2.one;root.offsetMin=root.offsetMax=Vector2.zero;Show(ScreenId.Home);}
 RectTransform Make(string n,Transform p){var g=new GameObject(n,typeof(RectTransform));g.transform.SetParent(p,false);return g.GetComponent<RectTransform>();}
 void Clear(){for(int i=root.childCount-1;i>=0;i--)Destroy(root.GetChild(i).gameObject);}
 void Show(ScreenId id){Clear();switch(id){case ScreenId.Home:Home();break;case ScreenId.Map:Map();break;case ScreenId.Loadout:Loadout();break;case ScreenId.Battle:Battle();break;case ScreenId.Result:Result();break;case ScreenId.Shop:Shop();break;case ScreenId.Missions:Missions();break;default:Settings();break;}}
 Text T(Transform p,string s,int z){var g=new GameObject("Text",typeof(Text));g.transform.SetParent(p,false);var t=g.GetComponent<Text>();t.font=Resources.GetBuiltinResource<Font>("Arial.ttf");t.text=s;t.fontSize=z;t.alignment=TextAnchor.MiddleCenter;t.color=Color.white;return t;}
 Button B(Transform p,string s,int z){var g=new GameObject("Button",typeof(Image),typeof(Button));g.transform.SetParent(p,false);g.GetComponent<Image>().color=new Color(.19f,.14f,.09f);var b=g.GetComponent<Button>();var t=T(g.transform,s,z);R(t,0,0,1000,100);return b;}
 void R(Graphic g,float x,float y,float w,float h){var r=g.rectTransform;r.anchorMin=r.anchorMax=new Vector2(.5f,.5f);r.anchoredPosition=new Vector2(x,y);r.sizeDelta=new Vector2(w,h);}
 void Header(string a,string b){var t=T(root,a,38);R(t,0,790,1080,70);var c=T(root,"🪙 "+coins,25);R(c,380,790,300,55);var s=T(root,b,18);s.color=new Color(.7f,.64f,.54f);R(s,0,720,1080,50);}
 void Add(string s,UnityEngine.Events.UnityAction a,ref float y){var b=B(root,s,27);R(b,0,y,900,82);b.onClick.AddListener(a);y-=100;}
 void Home(){Header("🏜️ حارس القافلة","طريق التجارة يبدأ من هنا");var h=T(root,"قافلة نجد\n\nاحمِ القافلة وطوّر معداتك وافتح طرقًا جديدة.",34);R(h,0,410,1080,300);float y=150;Add("ابدأ الرحلة ⚔️",()=>Show(ScreenId.Map),ref y);Add("التجهيز 🎒",()=>Show(ScreenId.Loadout),ref y);Add("المتجر 🛒",()=>Show(ScreenId.Shop),ref y);Add("المهام 📜",()=>Show(ScreenId.Missions),ref y);Add("الإعدادات ⚙️",()=>Show(ScreenId.Settings),ref y);}
 void Map(){Header("🗺️ خريطة القوافل","افتح الطرق واحدة تلو الأخرى");string[] a={"بوابة نجد","وادي الرمال","سوق الحجاز","طريق البحر","حصن الشمال"};float y=520;for(int i=0;i<a.Length;i++){var b=B(root,(i<level?"🟢 ":"🔒 ")+a[i]+" · المرحلة "+(i+1),23);R(b,0,y,980,100);if(i<level)b.onClick.AddListener(()=>Show(ScreenId.Loadout));y-=120;}var h=B(root,"الرئيسية",22);R(h,0,-780,900,80);h.onClick.AddListener(()=>Show(ScreenId.Home));}
 void Loadout(){Header("🎒 تجهيز القافلة","سعة الحمولة 10 — اختر أدواتك");var c=T(root,"السعة: "+weight+" / 10",24);R(c,0,650,1000,55);float y=550;for(int i=0;i<gear.Length;i++){int n=i;var b=B(root,(selected.Contains(i)?"✓ ":"")+gear[i],22);R(b,0,y,980,82);b.onClick.AddListener(()=>Toggle(n));y-=92;}var st=B(root,"ابدأ الدفاع ⚔️",28);R(st,0,-650,980,90);st.onClick.AddListener(()=>{if(weight>=6)Show(ScreenId.Battle);});}
 void Toggle(int i){int w=(i==1||i==3)?3:(i==4||i==5)?1:2;if(selected.Contains(i)){selected.Remove(i);weight-=w;}else if(weight+w<=10){selected.Add(i);weight+=w;}Show(ScreenId.Loadout);}
 void Battle(){Header("⚔️ الدفاع عن القافلة","اضغط الغزاة قبل وصولهم");var h=T(root,"❤️❤️❤️     موجة 1 / 3",26);R(h,0,650,1000,60);var s=T(root,"🌙\n\n🏰                         🐪\n\n     🗡️       🦂       🗡️",52);R(s,0,150,1000,800);float x=-280;foreach(string e in new[]{"🗡️","🦂","🗡️"}){var b=B(root,e,45);R(b,x,-250,180,120);b.onClick.AddListener(()=>{coins+=10;Destroy(b.gameObject);});x+=280;}var q=B(root,"انسحاب",22);R(q,0,-700,980,80);q.onClick.AddListener(()=>Show(ScreenId.Home));}
 void Result(){Header("🏆 وصلت القافلة","الجولة اكتملت");var t=T(root,"✨\n\nغنيمة الطريق\n+50 🪙",38);R(t,0,300,1000,360);coins+=50;level=Mathf.Min(5,level+1);var n=B(root,"التالي →",28);R(n,0,-300,980,90);n.onClick.AddListener(()=>Show(ScreenId.Map));}
 void Shop(){Header("🛒 سوق القافلة","مظاهر وأغراض تجميلية");string[] a={"🏜️ مظهر الصحراء — 80 🪙","🚩 راية القافلة — 120 🪙","🛡️ درع ذهبي — 180 🪙","🐪 جمل أسود — 250 🪙"};float y=520;foreach(var x in a){var b=B(root,x,23);R(b,0,y,980,100);y-=120;}var h=B(root,"رجوع",22);R(h,0,-780,900,80);h.onClick.AddListener(()=>Show(ScreenId.Home));}
 void Missions(){Header("📜 المهام","مكافآت يومية وتقدم مستمر");string[] a={"أكمل 3 جولات — 100 🪙","اهزم 15 غازيًا — 150 🪙","افتح طريقًا جديدًا — 200 🪙","احمِ القافلة دون خسارة — ⭐"};float y=520;foreach(var x in a){var b=B(root,x,22);R(b,0,y,980,100);y-=120;}var h=B(root,"رجوع",22);R(h,0,-780,900,80);h.onClick.AddListener(()=>Show(ScreenId.Home));}
 void Settings(){Header("⚙️ الإعدادات","الصوت واللغة وإدارة البيانات");string[] a={"🔊 الصوت: تشغيل","📳 الاهتزاز: تشغيل","🌐 اللغة: العربية","🗑️ إعادة التقدم"};float y=520;foreach(var x in a){var b=B(root,x,22);R(b,0,y,980,100);y-=120;}var h=B(root,"رجوع",22);R(h,0,-780,900,80);h.onClick.AddListener(()=>Show(ScreenId.Home));}
}